### ISSUE TITLE
Saves break when mod name contains special characters

### ISSUE THREAD

**Issue by jkulawik** [jkulawik/tdd-issues#1]
An example of this is `:` in the name. I'm not sure what was meant by "break" - whether the auto save fails quietly or whether the game crashes.

**Comment by crater0** [comment]
The saves (both auto saves and manual saves) just fail quietly, unless in debug mode where the following gets printed to the log: `ERROR: Unable to open serialized file '\Documents/Amnesia/Main/User/custom/2985343811_Amnesia:Chromanin/AutoSave_NULL_2023_12_6_12_47_9_0.sav' as w+! Invalid filepointer returned!`

**Comment by crater0** [comment]
`ERROR: Unable to open serialized file '\Documents/Amnesia/Main/butt/custom/2985343811_Amnesia:Chromanin/AutoSave_NULL_2023_12_6_12_47_9_0.sav' as w+! Invalid filepointer returned!` gets printed to the log when attempting to save.

**Comment by crater0** [comment]
`ERROR: Unable to open serialized file '\Documents/Amnesia/Main/User/custom/2985343811_Amnesia:Chromanin/AutoSave_NULL_2023_12_6_12_47_9_0.sav' as w+! Invalid filepointer returned!` gets printed to the log when attempting to save.

**Comment by crater0** [comment]
Issue still occurs on beta 1.51. Mod name in custom_story_settings.cfg needs to contain an invalid character, such as `:`, to trigger the issue.

**Comment by crater0** [comment]
This issue is fixed in build 14564714.
