### ISSUE TITLE
SetEffectVoiceOverCallback - Cached func handle call error crash after map change

### ISSUE THREAD

**Issue by crater0** [jkulawik/tdd-issues#12]
The game will crash if a voice line is played after a previous level set `SetEffectVoiceOverCallback`, or if the map is changed before the voice line that set `SetEffectVoiceOverCallback` finishes playing.

An error similar to `ERROR: Error calling cached script func handle '-null- :: x9é' - out of date` will be printed to the log.

Debug mode seems to prevent the crash (or at least make it less likely) and the following error can be seen: 
![image](https://github.com/jkulawik/tdd-issues/assets/16257718/38011823-7dd2-41d8-99ec-38c541995a41)

Steps to trigger the crash:
1. Add an EffectVoice line. 
2. Set a Voice Over callback.
3. Change level. doing so before the voice line finishes will cause the game to crash once the voice line finishes.
4. If voice line finished before changing map, playing another EffectVoice, or starting a Flashback, will trigger a crash after the voice line ends.

Only slightly related, but the EffectVoiceOverCallback behavior of not calling a pending callback on map change exists in all releases of the game and results in a few minor script issues where some flags never get set if the player gets to a level door quick enough.

**Comment by crater0** [comment]
I have been having trouble triggering this issue in simple test maps, simply changing levels several times is not enough to trigger the bug.

**Comment by crater0** [comment]
[EffectVoiceCallbackTest.zip](https://github.com/user-attachments/files/15524509/EffectVoiceCallbackTest.zip)

https://steamcommunity.com/sharedfiles/filedetails/?id=3259475560

Here is a map to test the issue. Just load the map then enter the door, either before or after the voice line finishes.

**Comment by jkulawik** [comment]
Should be fixed as of build 14591455

**Comment by crater0** [comment]
Confirmed fixed
