### ISSUE TITLE
Interaction crosshair appears for entities that cannot be interacted with

### ISSUE THREAD

**Issue by crater0** [jkulawik/tdd-issues#13]
Entities that can only be interacted with when they have an interaction callback set always appear to be interactable. 
 
Example: Object props of the Static subtype will appear to be interactable even when no interaction callback is set. Also affects props with StaticPhysics enabled.

Potential cause - CanInteract interact callback check always passes.
Need to test - Does this also affect OnInteract and other interaction callback checks?

Tested and affected: 
`cLuxProp_Object::CanInteract`
`cLuxProp_Lamp::CanInteract`

Untested entity types that contain an interact callback check: 
`cLuxProp_MoveObject::CanInteract`

Does not seem to affect `cLuxArea_Script::CanInteract`, but there could be related interact callback issues, will need to test more.

**Comment by jkulawik** [comment]
Should be fixed as of build 14591455

**Comment by crater0** [comment]
Partially fixed, introduced #17
