### ISSUE TITLE
Incorrect include file will be used if multiple mods use an include file with the same name

### ISSUE THREAD

**Issue by crater0** [jkulawik/tdd-issues#14]
If you load a custom story that uses include directives, then load a different custom story within the same session that also includes scripts with the same filename, the included script from the first mod will be used instead.

I created the following custom stories to test this issue. Please use debug mode to test.
https://steamcommunity.com/sharedfiles/filedetails/?id=3260355521
https://steamcommunity.com/sharedfiles/filedetails/?id=3260356414

Load either one first, observe the debug message that is printed.
Exit to main menu and then load the second custom story. The debug message should be different, but the original message will be printed instead.

This seems to also affect global.hps and inventory.hps for custom stories. If included in your mod and added to a map script via `#include "global.hps"`, attempting to call any new functions in them result in a No Matching Signature error (since the functions don't exist in the retail files). https://github.com/jkulawik/tdd-issues/issues/14#issuecomment-2145036319

**Comment by jkulawik** [comment]
Which build ID? If older than 14535231 I can add a new tag

**Comment by crater0** [comment]
This bug is present in stable 1.5 (12590639), as well as both 1.51 builds.

**Comment by crater0** [comment]
I also made a custom story showing off the #include global.hps issue. If the correct global file is loaded, the mod will start fine. Otherwise, it'll fail with a No Matching Signature error due to loading the retail file instead.

https://steamcommunity.com/sharedfiles/filedetails/?id=3260371357

**Comment by jkulawik** [comment]
Should be fixed as of build 14591455

**Comment by crater0** [comment]
Confirmed fixed.
