### ISSUE TITLE
Remapped callbacks crash the game when not in debug mode

### ISSUE THREAD

**Issue by crater0** [jkulawik/tdd-issues#15]
When playing without debug mode, when a callback is created that needs to be remapped (ie via AddTimer), the game will crash.

I created a small test map to repro this issue. When loaded without debug mode, the game will crash. When loaded with debug mode it will show the 'resolved remapped callback' warning.

https://steamcommunity.com/sharedfiles/filedetails/?id=3260414737

**Comment by jkulawik** [comment]
Should be fixed as of build 14591455

**Comment by crater0** [comment]
Fixed in 14591455
