### ISSUE TITLE
Issues with resolving the paths to mod `global.hps` and `inventory.hps` when reloading a map in debug mode

### ISSUE THREAD

**Issue by jkulawik** [jkulawik/tdd-issues#2]
"From what I understand, it's only in debug, so not sure if it's really that much of an issue"

**Comment by crater0** [comment]
"reloading a mod during development incorrectly loads the retail Global.hps and Inventory.hps instead of loading the custom story versions."
it is specifically triggered when refreshing a map (F2) or loading a map manually through the debug menu

**Comment by crater0** [comment]
This issue is FIXED in 1.51.

**Comment by jkulawik** [comment]
So this was a 1.5 bug?
