### ISSUE TITLE
Lights crashing the editors

### ISSUE THREAD

**Issue by jkulawik** [jkulawik/tdd-issues#4]
> I found a whoopsie. Can you see if you can repro it, @Mudbill, or anyone, when you get a chance? In ModelEditor, placing a light or loading an ent with a light crashes ModelEditor. Seems like the similar issue in LevelEditor, but I'm not sure if it could be caused be me and my shenanigans. I think I have the right editor versions, but I might have messed it up.

**Comment by crater0** [comment]
This is still occurring in 1.51 build 14564714.

Steps to trigger this crash: Start ModelEditor.exe and try to place a light. Editor will crash with a memory access violation.

![image](https://github.com/jkulawik/tdd-issues/assets/16257718/aa676792-34ce-4cdd-8f6b-234f9fb5b899)

**Comment by Mudbill** [comment]
I confirm the crash upon placing a light. The BlackBox pop-up seemingly also crashed lol (only showed the "gathering info" stage, then disappeared).

**Comment by jkulawik** [comment]
Should be fixed as of build 14591455

**Comment by crater0** [comment]
Fixed, but introduced #16.
