### ISSUE TITLE
Colors with all RGBA channels set to 255 aren't getting applied

### ISSUE THREAD

**Issue by jkulawik** [jkulawik/tdd-issues#5]
> Also, a weird one - in the new colour picker, which mostly works wonderfully, until... repro: 
> * Open a colour picker in ParticleEditor, LevelEditor etc. Set the colour to white, with alpha < 255, click OK. Colour should be applied successfully.
> * Re-open the picker. Now try any colour other than white, with full alpha, click OK. Colour should be applied successfully again.
> * Re-open the picker. This time set the colour to white and the alpha to full at the same time. Click OK. The new colour isn't applied, as if you had clicked cancel.
> 
> Seems like you can't set all 4 RGBA channels to 255 at once, as if that's counted as an invalid colour. Is there a checksum that looks for <255*4 instead of <=, or something like that?

**Comment by crater0** [comment]
This is still occurring on 1.51 build 14564714.

Screenshot showing light diffuse color not being able to be set to 255,255,255
![image](https://github.com/jkulawik/tdd-issues/assets/16257718/3879140a-b464-4be6-b048-7a99d26e1475)

After pressing OK:
![image](https://github.com/jkulawik/tdd-issues/assets/16257718/bcefdbf8-b954-4013-8f68-024948428fdc)

**Comment by jkulawik** [comment]
Should be fixed as of build 14591455

**Comment by crater0** [comment]
Confirmed fixed in 14591455
