### ISSUE TITLE
One of the thaler chest text entries is hardcoded and can't be overridden

### ISSUE THREAD

**Issue by jkulawik** [jkulawik/tdd-issues#7]
Most of the thaler texts can be overwritten through the lang files. However, one of them permanently says "thalers".

At the moment I don't remember which exact text this is, it has to be tested.

**Comment by jkulawik** [comment]
Fixed in build-id:14564714 but needs testing

**Comment by crater0** [comment]
New lang entry is being used but leading and trailing spaces are being removed. This also affects the default lang entry.
The other chest lang entries do not contain a leading or trailing space and instead its added automatically, perhaps the locked chest message should also behave this way.

![image](https://github.com/jkulawik/tdd-issues/assets/16257718/7496ee38-668e-4ba6-9fe2-31ab7ca946fb)

**Comment by jkulawik** [comment]
Should be fixed as of build 14591455

**Comment by crater0** [comment]
Confirmed fixed.
